imports:
    - { resource: alias.yml }

services:
    _defaults:
        autowire: true
        bind:
            $ext_images_path: '%core.root_path%ext/david63/autodbbackup/adm/style/images'
        public: true

    david63.biblequotes.listener:
        class: david63\biblequotes\event\listener
        tags:
            - { name: event.listener }

    david63.biblequotes.admin.controller:
        class: david63\biblequotes\controller\admin_controller

    david63.biblequotes.core.functions:
        class: david63\biblequotes\core\functions
