services:
    david63.biblequotes.listener:
        class: david63\biblequotes\event\listener
        arguments:
            - '@config'
            - '@template'
        tags:
            - { name: event.listener }

    david63.biblequotes.admin.controller:
        class: david63\biblequotes\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '@david63.biblequotes.core.functions'

    david63.biblequotes.core.functions:
        class: david63\biblequotes\core\functions
        arguments:
            - '@ext.manager'

    _defaults:
        public: true
